---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko-reg
spec:
  containers:
  - name: kaniko
    image: ghostwritten/kaniko-project-executor:latest 
    args: ["--dockerfile=/workspace/Dockerfile",
            "--context=dir://workspace",
            "--skip-tls-verify",
            "--destination=192.168.10.80:5000/devops-toolkit:1.0.0"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: workspace
        mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred2
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: workspace
      hostPath: 
        path: /root/kaniko/kaniko-demo 
